# Generated by Django 4.0.4 on 2022-05-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leave_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='end_date',
            field=models.DateField(default='2022-05-27'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='start_date',
            field=models.DateField(default='2022-06-10'),
            preserve_default=False,
        ),
    ]
